name: CD
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: known_hosts
        if_key_exists: replace

    - name: Login to server and create file
      run: ssh -o StrictHostKeyChecking=no $username@$host 'mkdir -p ~/AVK && touch ~/AVK/task41.txt'
      env:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}